name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Agregar paso para instalar dependencias y construir
      - name: Install dependencies and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      # Desplegar en Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INKFED_F18A9 }}
          channelId: live
          projectId: inkfed-90f15
